'use client';

import { createContext, useContext, useState, useEffect, useCallback } from 'react';

export type Language = 'en' | 'ru' | 'es' | 'id' | 'hi' | 'fa';

interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'en',
  setLang: () => {},
  t: (key: string) => key,
});

export function useLanguage() {
  return useContext(LanguageContext);
}

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.ads': 'Ads',
    'nav.tasks': 'Tasks',
    'nav.refer': 'Refer',
    'nav.profile': 'Profile',
    'home.balance': 'Balance',
    'home.quickActions': 'Quick Actions',
    'home.earnMore': 'Earn More',
    'home.dailyBonus': 'Daily Bonus',
    'home.rewardCode': 'Reward Code',
    'home.withdraw': 'Withdraw',
    'home.leaderboard': 'Leaderboard',
    'home.watchAds': 'Watch Ads',
    'home.tasks': 'Tasks',
    'home.refer': 'Refer Friends',
    'ads.watchAds': 'Watch Ads',
    'ads.visitSites': 'Visit Sites',
    'ads.todayEarned': 'Today Earned',
    'ads.available': 'Available',
    'ads.watchAd': 'Watch Ad',
    'ads.visitWebsite': 'Visit Website',
    'ads.visitedToday': 'Visited Today',
    'ads.allAdsDone': 'All ads watched for today! Come back tomorrow after daily reset (00:00 UTC).',
    'tasks.title': 'Tasks',
    'tasks.subtitle': 'Complete tasks to earn Hive',
    'tasks.main': 'Main',
    'tasks.partner': 'Partner',
    'tasks.community': 'Community',
    'tasks.completed': 'Completed',
    'tasks.verify': 'Verify',
    'tasks.join': 'Join',
    'tasks.start': 'Start',
    'tasks.noTasks': 'No tasks in this category yet',
    'wallet.title': 'Wallet',
    'wallet.balance': 'Balance',
    'wallet.withdraw': 'Withdraw',
    'wallet.setWallet': 'Set Wallet',
    'wallet.transactions': 'Transactions',
    'daily.title': 'Daily Bonus',
    'daily.claim': 'Claim Bonus',
    'daily.claimed': 'Claimed Today',
    'reward.title': 'Reward Code',
    'reward.placeholder': 'Enter reward code',
    'reward.claim': 'Claim',
    'referral.title': 'Refer Friends',
    'referral.share': 'Share Referral Link',
    'referral.copy': 'Copy',
    'referral.claim': 'Claim Rewards',
    'profile.title': 'Profile',
    'profile.about': 'About Hive Earn',
    'profile.notifications': 'Notifications',
    'profile.settings': 'Settings',
    'profile.language': 'Language',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.loading': 'Loading...',
    'common.error': 'Something went wrong',
    'common.success': 'Success',
    'about.title': 'About Hive Earn',
  },
  ru: {
    'nav.home': 'Главная',
    'nav.ads': 'Реклама',
    'nav.tasks': 'Задания',
    'nav.refer': 'Рефералы',
    'nav.profile': 'Профиль',
    'home.balance': 'Баланс',
    'home.quickActions': 'Быстрые действия',
    'home.earnMore': 'Зарабатывать больше',
    'home.dailyBonus': 'Ежедневный бонус',
    'home.rewardCode': 'Код награды',
    'home.withdraw': 'Вывод',
    'home.leaderboard': 'Лидеры',
    'home.watchAds': 'Смотреть рекламу',
    'home.tasks': 'Задания',
    'home.refer': 'Пригласить друзей',
    'ads.watchAds': 'Смотреть рекламу',
    'ads.visitSites': 'Посетить сайты',
    'ads.todayEarned': 'Заработано сегодня',
    'ads.available': 'Доступно',
    'ads.watchAd': 'Смотреть рекламу',
    'ads.visitWebsite': 'Посетить сайт',
    'ads.visitedToday': 'Посещено сегодня',
    'ads.allAdsDone': 'Вся реклама просмотрена! Возвращайтесь завтра после сброса (00:00 UTC).',
    'tasks.title': 'Задания',
    'tasks.subtitle': 'Выполняйте задания для заработка',
    'tasks.main': 'Основные',
    'tasks.partner': 'Партнеры',
    'tasks.community': 'Сообщество',
    'tasks.completed': 'Выполнено',
    'tasks.verify': 'Проверить',
    'tasks.join': 'Присоединиться',
    'tasks.start': 'Начать',
    'tasks.noTasks': 'В этой категории нет заданий',
    'wallet.title': 'Кошелек',
    'wallet.balance': 'Баланс',
    'wallet.withdraw': 'Вывести',
    'wallet.setWallet': 'Установить кошелек',
    'wallet.transactions': 'Транзакции',
    'daily.title': 'Ежедневный бонус',
    'daily.claim': 'Получить бонус',
    'daily.claimed': 'Получено сегодня',
    'reward.title': 'Код награды',
    'reward.placeholder': 'Введите код награды',
    'reward.claim': 'Получить',
    'referral.title': 'Пригласить друзей',
    'referral.share': 'Поделиться ссылкой',
    'referral.copy': 'Копировать',
    'referral.claim': 'Получить награды',
    'profile.title': 'Профиль',
    'profile.about': 'О Hive Earn',
    'profile.notifications': 'Уведомления',
    'profile.settings': 'Настройки',
    'profile.language': 'Язык',
    'common.cancel': 'Отмена',
    'common.confirm': 'Подтвердить',
    'common.loading': 'Загрузка...',
    'common.error': 'Что-то пошло не так',
    'common.success': 'Успешно',
    'about.title': 'О Hive Earn',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.ads': 'Anuncios',
    'nav.tasks': 'Tareas',
    'nav.refer': 'Referidos',
    'nav.profile': 'Perfil',
    'home.balance': 'Saldo',
    'home.quickActions': 'Acciones rápidas',
    'home.earnMore': 'Ganar más',
    'home.dailyBonus': 'Bono diario',
    'home.rewardCode': 'Código de recompensa',
    'home.withdraw': 'Retirar',
    'home.leaderboard': 'Clasificación',
    'home.watchAds': 'Ver anuncios',
    'home.tasks': 'Tareas',
    'home.refer': 'Invitar amigos',
    'ads.watchAds': 'Ver anuncios',
    'ads.visitSites': 'Visitar sitios',
    'ads.todayEarned': 'Ganado hoy',
    'ads.available': 'Disponible',
    'ads.watchAd': 'Ver anuncio',
    'ads.visitWebsite': 'Visitar sitio',
    'ads.visitedToday': 'Visitado hoy',
    'ads.allAdsDone': '¡Todos los anuncios vistos por hoy! Vuelve mañana después del reinicio (00:00 UTC).',
    'tasks.title': 'Tareas',
    'tasks.subtitle': 'Completa tareas para ganar Hive',
    'tasks.main': 'Principal',
    'tasks.partner': 'Socio',
    'tasks.community': 'Comunidad',
    'tasks.completed': 'Completado',
    'tasks.verify': 'Verificar',
    'tasks.join': 'Unirse',
    'tasks.start': 'Iniciar',
    'tasks.noTasks': 'No hay tareas en esta categoría',
    'wallet.title': 'Cartera',
    'wallet.balance': 'Saldo',
    'wallet.withdraw': 'Retirar',
    'wallet.setWallet': 'Configurar cartera',
    'wallet.transactions': 'Transacciones',
    'daily.title': 'Bono diario',
    'daily.claim': 'Reclamar bono',
    'daily.claimed': 'Reclamado hoy',
    'reward.title': 'Código de recompensa',
    'reward.placeholder': 'Ingresa el código',
    'reward.claim': 'Reclamar',
    'referral.title': 'Invitar amigos',
    'referral.share': 'Compartir enlace',
    'referral.copy': 'Copiar',
    'referral.claim': 'Reclamar recompensas',
    'profile.title': 'Perfil',
    'profile.about': 'Acerca de Hive Earn',
    'profile.notifications': 'Notificaciones',
    'profile.settings': 'Configuración',
    'profile.language': 'Idioma',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.loading': 'Cargando...',
    'common.error': 'Algo salió mal',
    'common.success': 'Éxito',
    'about.title': 'Acerca de Hive Earn',
  },
  id: {
    'nav.home': 'Beranda',
    'nav.ads': 'Iklan',
    'nav.tasks': 'Tugas',
    'nav.refer': 'Referral',
    'nav.profile': 'Profil',
    'home.balance': 'Saldo',
    'home.quickActions': 'Aksi Cepat',
    'home.earnMore': 'Hasilkan Lebih',
    'home.dailyBonus': 'Bonus Harian',
    'home.rewardCode': 'Kode Hadiah',
    'home.withdraw': 'Tarik',
    'home.leaderboard': 'Papan Peringkat',
    'home.watchAds': 'Tonton Iklan',
    'home.tasks': 'Tugas',
    'home.refer': 'Undang Teman',
    'ads.watchAds': 'Tonton Iklan',
    'ads.visitSites': 'Kunjungi Situs',
    'ads.todayEarned': 'Diperoleh Hari Ini',
    'ads.available': 'Tersedia',
    'ads.watchAd': 'Tonton Iklan',
    'ads.visitWebsite': 'Kunjungi Situs',
    'ads.visitedToday': 'Dikunjungi Hari Ini',
    'ads.allAdsDone': 'Semua iklan telah ditonton! Kembali besok setelah reset (00:00 UTC).',
    'tasks.title': 'Tugas',
    'tasks.subtitle': 'Selesaikan tugas untuk mendapatkan Hive',
    'tasks.main': 'Utama',
    'tasks.partner': 'Mitra',
    'tasks.community': 'Komunitas',
    'tasks.completed': 'Selesai',
    'tasks.verify': 'Verifikasi',
    'tasks.join': 'Gabung',
    'tasks.start': 'Mulai',
    'tasks.noTasks': 'Belum ada tugas di kategori ini',
    'wallet.title': 'Dompet',
    'wallet.balance': 'Saldo',
    'wallet.withdraw': 'Tarik',
    'wallet.setWallet': 'Atur Dompet',
    'wallet.transactions': 'Transaksi',
    'daily.title': 'Bonus Harian',
    'daily.claim': 'Klaim Bonus',
    'daily.claimed': 'Diklaim Hari Ini',
    'reward.title': 'Kode Hadiah',
    'reward.placeholder': 'Masukkan kode hadiah',
    'reward.claim': 'Klaim',
    'referral.title': 'Undang Teman',
    'referral.share': 'Bagikan Tautan',
    'referral.copy': 'Salin',
    'referral.claim': 'Klaim Hadiah',
    'profile.title': 'Profil',
    'profile.about': 'Tentang Hive Earn',
    'profile.notifications': 'Notifikasi',
    'profile.settings': 'Pengaturan',
    'profile.language': 'Bahasa',
    'common.cancel': 'Batal',
    'common.confirm': 'Konfirmasi',
    'common.loading': 'Memuat...',
    'common.error': 'Terjadi kesalahan',
    'common.success': 'Berhasil',
    'about.title': 'Tentang Hive Earn',
  },
  hi: {
    'nav.home': 'होम',
    'nav.ads': 'विज्ञापन',
    'nav.tasks': 'कार्य',
    'nav.refer': 'रेफर',
    'nav.profile': 'प्रोफ़ाइल',
    'home.balance': 'बैलेंस',
    'home.quickActions': 'त्वरित क्रियाएं',
    'home.earnMore': 'अधिक कमाएं',
    'home.dailyBonus': 'दैनिक बोनस',
    'home.rewardCode': 'रिवॉर्ड कोड',
    'home.withdraw': 'निकासी',
    'home.leaderboard': 'लीडरबोर्ड',
    'home.watchAds': 'विज्ञापन देखें',
    'home.tasks': 'कार्य',
    'home.refer': 'दोस्तों को आमंत्रित करें',
    'ads.watchAds': 'विज्ञापन देखें',
    'ads.visitSites': 'साइट देखें',
    'ads.todayEarned': 'आज कमाया',
    'ads.available': 'उपलब्ध',
    'ads.watchAd': 'विज्ञापन देखें',
    'ads.visitWebsite': 'साइट देखें',
    'ads.visitedToday': 'आयोजित देखा',
    'ads.allAdsDone': 'आज के लिए सभी विज्ञापन देख लिए! कल रीसेट के बाद आएं (00:00 UTC)।',
    'tasks.title': 'कार्य',
    'tasks.subtitle': 'Hive कमाने के लिए कार्य पूरे करें',
    'tasks.main': 'मुख्य',
    'tasks.partner': 'साझेदार',
    'tasks.community': 'समुदाय',
    'tasks.completed': 'पूर्ण',
    'tasks.verify': 'सत्यापित करें',
    'tasks.join': 'जुड़ें',
    'tasks.start': 'शुरू करें',
    'tasks.noTasks': 'इस श्रेणी में कोई कार्य नहीं',
    'wallet.title': 'वॉलेट',
    'wallet.balance': 'बैलेंस',
    'wallet.withdraw': 'निकासी',
    'wallet.setWallet': 'वॉलेट सेट करें',
    'wallet.transactions': 'लेनदेन',
    'daily.title': 'दैनिक बोनस',
    'daily.claim': 'बोनस का दावा करें',
    'daily.claimed': 'आयोजित दावा',
    'reward.title': 'रिवॉर्ड कोड',
    'reward.placeholder': 'रिवॉर्ड कोड दर्ज करें',
    'reward.claim': 'दावा करें',
    'referral.title': 'दोस्तों को आमंत्रित करें',
    'referral.share': 'रेफरल लिंक साझा करें',
    'referral.copy': 'कॉपी',
    'referral.claim': 'रिवॉर्ड का दावा करें',
    'profile.title': 'प्रोफ़ाइल',
    'profile.about': 'Hive Earn के बारे में',
    'profile.notifications': 'सूचनाएं',
    'profile.settings': 'सेटिंग्स',
    'profile.language': 'भाषा',
    'common.cancel': 'रद्द करें',
    'common.confirm': 'पुष्टि करें',
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'कुछ गलत हुआ',
    'common.success': 'सफल',
    'about.title': 'Hive Earn के बारे में',
  },
  fa: {
    'nav.home': 'خانه',
    'nav.ads': 'تبلیغات',
    'nav.tasks': 'وظایف',
    'nav.refer': 'دعوت',
    'nav.profile': 'پروفایل',
    'home.balance': 'موجودی',
    'home.quickActions': 'اقدامات سریع',
    'home.earnMore': 'بیشتر کسب کنید',
    'home.dailyBonus': 'پاداش روزانه',
    'home.rewardCode': 'کد پاداش',
    'home.withdraw': 'برداشت',
    'home.leaderboard': 'جدول رده‌بندی',
    'home.watchAds': 'تماشای تبلیغات',
    'home.tasks': 'وظایف',
    'home.refer': 'دعوت دوستان',
    'ads.watchAds': 'تماشای تبلیغات',
    'ads.visitSites': 'بازدید سایت‌ها',
    'ads.todayEarned': 'امروز کسب شد',
    'ads.available': 'موجود',
    'ads.watchAd': 'تماشای تبلیغ',
    'ads.visitWebsite': 'بازدید سایت',
    'ads.visitedToday': 'امروز بازدید شد',
    'ads.allAdsDone': 'همه تبلیغات امروز دیده شد! فردا بعد از ریست برگردید (00:00 UTC).',
    'tasks.title': 'وظایف',
    'tasks.subtitle': 'برای کسب Hive وظایف را کامل کنید',
    'tasks.main': 'اصلی',
    'tasks.partner': 'همکار',
    'tasks.community': 'جامعه',
    'tasks.completed': 'تکمیل شد',
    'tasks.verify': 'تأیید',
    'tasks.join': 'پیوستن',
    'tasks.start': 'شروع',
    'tasks.noTasks': 'هیچ وظیفه‌ای در این دسته نیست',
    'wallet.title': 'کیف پول',
    'wallet.balance': 'موجودی',
    'wallet.withdraw': 'برداشت',
    'wallet.setWallet': 'تنظیم کیف پول',
    'wallet.transactions': 'تراکنش‌ها',
    'daily.title': 'پاداش روزانه',
    'daily.claim': 'دریافت پاداش',
    'daily.claimed': 'امروز دریافت شد',
    'reward.title': 'کد پاداش',
    'reward.placeholder': 'کد پاداش را وارد کنید',
    'reward.claim': 'دریافت',
    'referral.title': 'دعوت دوستان',
    'referral.share': 'اشتراک لینک دعوت',
    'referral.copy': 'کپی',
    'referral.claim': 'دریافت پاداش',
    'profile.title': 'پروفایل',
    'profile.about': 'درباره Hive Earn',
    'profile.notifications': 'اطلاعیه‌ها',
    'profile.settings': 'تنظیمات',
    'profile.language': 'زبان',
    'common.cancel': 'لغو',
    'common.confirm': 'تأیید',
    'common.loading': 'در حال بارگذاری...',
    'common.error': 'مشکلی پیش آمد',
    'common.success': 'موفق',
    'about.title': 'درباره Hive Earn',
  },
};

// Map Telegram language_code to our supported languages
function mapLanguageCode(code: string | undefined): Language {
  if (!code) return 'en';
  const map: Record<string, Language> = {
    en: 'en', ru: 'ru', es: 'es', id: 'id', hi: 'hi', fa: 'fa',
    uk: 'ru', be: 'ru', kk: 'ru',
    pt: 'es', it: 'es', fr: 'es',
  };
  return map[code] ?? 'en';
}

export function LanguageProvider({ children, telegramLangCode }: { children: React.ReactNode; telegramLangCode?: string }) {
  const [lang, setLangState] = useState<Language>('en');

  useEffect(() => {
    // Try to load from localStorage first, then fall back to Telegram language
    const saved = typeof window !== 'undefined' ? localStorage.getItem('hive_lang') as Language | null : null;
    if (saved && translations[saved]) {
      setLangState(saved);
    } else {
      setLangState(mapLanguageCode(telegramLangCode));
    }
  }, [telegramLangCode]);

  const setLang = useCallback((newLang: Language) => {
    setLangState(newLang);
    if (typeof window !== 'undefined') localStorage.setItem('hive_lang', newLang);
  }, []);

  const t = useCallback((key: string): string => {
    return translations[lang]?.[key] ?? translations.en[key] ?? key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const supportedLanguages: { code: Language; label: string; flag: string }[] = [
  { code: 'en', label: 'English', flag: '🇬🇧' },
  { code: 'ru', label: 'Русский', flag: '🇷🇺' },
  { code: 'es', label: 'Español', flag: '🇪🇸' },
  { code: 'id', label: 'Indonesia', flag: '🇮🇩' },
  { code: 'hi', label: 'हिन्दी', flag: '🇮🇳' },
  { code: 'fa', label: 'فارسی', flag: '🇮🇷' },
];
